# Generated by Django 2.2.6 on 2019-11-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='social_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
