# Generated by Django 2.2.6 on 2019-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20191101_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('contact_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'contact',
                'db_table': 'contact',
            },
        ),
    ]
