# Generated by Django 2.2.6 on 2019-11-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20191104_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realuser',
            name='address',
        ),
    ]
