# Generated by Django 2.2.6 on 2019-11-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20191104_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_caption', models.CharField(blank=True, max_length=100, null=True)),
                ('about_content', models.CharField(blank=True, max_length=255, null=True)),
                ('about_image', models.FileField(blank=True, null=True, upload_to='')),
                ('about_icons', models.FileField(blank=True, null=True, upload_to='')),
                ('about_number', models.CharField(blank=True, max_length=100, null=True)),
                ('about_iconitem', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'about',
                'db_table': 'about',
            },
        ),
        migrations.AlterModelOptions(
            name='imageslider',
            options={'verbose_name_plural': 'Image Slider'},
        ),
    ]
