# Generated by Django 2.2.6 on 2019-11-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20191105_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_icons', models.FileField(blank=True, null=True, upload_to='')),
                ('about_number', models.CharField(blank=True, max_length=100, null=True)),
                ('about_iconitem', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Child',
                'db_table': 'aboutchild',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_iconitem',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_icons',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_number',
        ),
    ]
