# Generated by Django 2.2.6 on 2019-11-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20191105_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
