# Generated by Django 2.2.6 on 2019-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_googlemap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlemap',
            options={'verbose_name_plural': 'Google Map'},
        ),
        migrations.RemoveField(
            model_name='googlemap',
            name='position',
        ),
        migrations.AddField(
            model_name='googlemap',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='googlemap',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='googlemap',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
