# Generated by Django 2.2.6 on 2019-11-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_rating_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Sliders'},
        ),
    ]
