# Generated by Django 2.2.6 on 2019-11-11 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_auto_20191108_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutchild',
            name='about_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caption', to='blogapp.About'),
        ),
    ]
